[build]
command = 'npm run build'
functions = 'functions'

[[redirects]]
  from = "/api/weather/hourly/*"
  to = "/.netlify/functions/weather-hourly/:splat"
[[redirects]]
  from = "/api/weather/*"
  to = "/.netlify/functions/weather/:splat"

[[redirects]]
  from = "/api/places/*"
  to = "/.netlify/functions/places/:splat"

[[redirects]]
  from = "/api/place-photo/*"
  to = "/.netlify/functions/photo-url/:splat"

  [functions]
  node_bundler = "esbuild"